### ISSUE TITLE
metascraper-video returning null values including example url

### ISSUE THREAD

**Issue by lumberbeard** [microlinkhq/metascraper#108]
### Prerequisites

- [Yes ] I'm using the last version.
    "metascraper": "^4.0.0",
    "metascraper-video": "^4.0.0",
- [Yes ] My node version is the same as declared as `package.json`.
  v8.9.3
  "got" installed fresh

### Subject of the issue

Using other modules works fine, however, metascraper-video does not.
I'm simply trying to extract the video url.
Using your example included in your test documentation, i'm getting a null value for video as well as every other news site url.

```
const metascraper = require('metascraper')([
  require('metascraper-video')()
])  
  const got = require('got')
    const targetUrl = 'https://www.theverge.com/2018/1/22/16921092/pentagon-secret-nuclear-bunker-reconstruction-minecraft-cns-miis-model'
  
  ;(async () => {
    const {body: html, url} = await got(targetUrl)
    const metadata = await metascraper({html, url})
      console.log(metadata)
  })()
```

Interactive example: https://runkit.com/kikobeats/5b81bc8707c43a0012774b36

### Steps to reproduce

Put in the code above.

### Expected behaviour

Expecting get a usable video url.

### Actual behaviour

Null value.

**Comment by Kikobeats** [comment]
That's because the metascraper-video [rules](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-video/index.js#L44) are not detecting a [video url](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-video/index.js#L8).

For satisfying this condition the url extracted need to have an extension, like `.mp4`.

Try loading [metascraper-video-provider](https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-video-provider) or [passing your own custom rules as parameter](https://metascraper.js.org/#/?id=rules-1).
