### ISSUE TITLE
Keywords from meta tags or content

### ISSUE THREAD

**Issue by kulakowka** [microlinkhq/metascraper#21]
[Embedly](http://embed.ly/code) for example can be given keywords. Could you add such functionality?

**Comment by Kikobeats** [comment]
Probably related with https://github.com/ianstormtaylor/metascraper/issues/4

**Comment by Kikobeats** [comment]
The trend is not to use meta tag keywords because it reveals to your competitors your interested keywords for position your website in SEO terms.

Also, it doesn't count for SEO
https://www.youtube.com/watch?v=jK7IPbnmvVU

This doesn't mean we can use it, for example, know the topics related with the web we are extracting metadata, but the point is we need to define fallbacks if `keywords` is not present in the HTML markup.

**Comment by Kikobeats** [comment]
I'm going to close that because I don't feel keywords relevant information to be extracted.
