### ISSUE TITLE
Metascraper getting stuck on GDPR consent page

### ISSUE THREAD

**Issue by kristoferlund** [microlinkhq/metascraper#216]
Hi, 

Metascraper is unable to scrape the following page:

`https://www.washingtonpost.com/opinions/jeff-flake-fellow-republicans-theres-still-time-to-save-your-souls/2019/09/30/ade876f6-e2d3-11e9-b403-f738899982d2_story.html`

Washington Post serves its GDPR consent page instead of the requested page. 

Response:
```
{ author: null,
  date: null,
  description: null,
  image:
   'https://www.washingtonpost.com/pbox.php?url=https://www.washingtonpost.com/pb/resources/img/twp-social-share.png&w=1484&op=resize&opt=1&filter=antialias&t=20170517',
  logo:
   'https://www.washingtonpost.com/pb/resources/img/thewashingtonpost-black-400x60.png',
  publisher: 'The Washington Post',
  title: '- The Washington Post',
  url: 'https://www.washingtonpost.com/gdpr-consent/' }
```

Washington Post does this, and probably a number of other sites as well. 

This is most likely not an issue with Metascraper but I'd thougth it would be a good idea to raise the issue anyway. Perhaps this is a discussion for another forum. Any ideas on how to work around a thing like this?

**Comment by Kikobeats** [comment]
You're, this is not part of metascraper universe 🙂

I recommend you take a look to https://github.com/paulirish/headless-cat-n-mouse

Although I feel there is not too much to do there: some websites (like Washington) ban your requests because they detect the IP address come from a data center.

The thing you need to bypass this check is a residential proxy IP; They're expensive so probably you need to do this at scale to be worth it.

I have widely experience under these situations since I'm running [microlink API](https://microlink.io)

Feel free to [ping me on Twitter](https://twitter.com/kikobeats), happy to share some knowledge over this!
