### ISSUE TITLE
Link preview selects aria-hidden image at yandex.ru

### ISSUE THREAD

**Issue by Salmela** [microlinkhq/metascraper#253]
### Prerequisites

- [X] I'm using the last version.

I am using the paid plan of microlink api.

### Subject of the issue

Microlink selects 1x1 image as link preview for `yandex.ru`.

### Steps to reproduce

This request to microlink api currently reproduces the issue `http://api.microlink.io/?url=https://yandex.ru`.

### Expected behaviour

I expected the page to just give the apple-touch-icon/favicon. And the link preview probably should not select image element that has `aria-hidden=true` attribute.

### Actual behaviour
The link preview had 1x1px white image, from the following html element.
```html
<img aria-hidden="true" class="b-icon inline-stocks__more-icon" src="//yastatic.net/lego/_/La6qi18Z8LwgnZdsAr1qy1GwCwo.gif"/>
```

**Comment by Kikobeats** [comment]
Thanks for reporting!

It's happening because `yandex.ru` doesn't have a shareable image as part of his HTML markup (they aren't using Open Graph, or Twitter meta tags, or Google item prop)

Because that, the parser is trying to get an image, using some fuzzy rules based on very generic DOM selectors, like `$('img')`:

https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-image/index.js#L21

I agree that probably the parser should skip images with `aria-hidden="true"`, but I'm not seeing any useful image on the website that could be used as an image preview.

So, in your opinion, what image should be detected as a good image?

**Comment by Salmela** [comment]
I would really prefer that the `image` in Microlink api would just give null so that our code would fallback to the `logo` which looks correct.

**Comment by Kikobeats** [comment]
Thanks for clarifying 🙂

This is the rule that is causing the current image url:
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-image/index.js#L24

It could be updated to consider don't extract `img` with `aria-hidden="true"`:

```
toImage($ => $('img[src]:not([aria-hidden="true"])').attr('src'))
```

However, doing that causes a different but not useful image will be considered as an image:

```json
{
  "image: "https://avatars.mds.yandex.net/get-banana/60828/x2530VN_pHBif1LR0OTD0Hbz_banana_20161021_landhd.png/optimize"
}
```

![](https://avatars.mds.yandex.net/get-banana/60828/x2530VN_pHBif1LR0OTD0Hbz_banana_20161021_landhd.png/optimize)

**Comment by Salmela** [comment]
Hi thanks for troubleshooting this issue.
We are not using the react components of Microlink, but we will most likely implement similar solution in our backend.
I have no preference over either solution, but both of them seems sensible to me.

**Comment by Kikobeats** [comment]
Released ignoring `aria-hidden="true"` images at metascraper v5.9.4.

Also, deployed into Microlink API endpoint:

https://api.microlink.io/?url=https://yandex.ru
