### ISSUE TITLE
[metascraper-author] Rules priorities

### ISSUE THREAD

**Issue by tbell511** [microlinkhq/metascraper#48]
It appears that there is an unintended 'a' in line 50 of the author package.  In my test's this is causing poor results for the author. 
> strict(wrap($ => getValue($, $('[class*="author"] a')))),

Using this url, you will find that metascraper returns "Shakespeare Videos" for author
http://www.sparknotes.com/shakespeare/macbeth/quotes.html

Removing the random "a" on line 50, returns the correct author, "William Shakespeare"
> strict(wrap($ => getValue($, $('[class*="author"]')))),

However, there are other URL's that only successfuly extract the Authors name when that 'a' is present.  What exactly is that "a" doing?

Thanks,

**Comment by Kikobeats** [comment]
Thanks for open this issue!

The reason why this kind of rules exists is related with old websites. They don't have metadata tags, like open graph or twitter, so we need to do a little of science mad.

The rule that you said is already present:
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-author/index.js#L53

The problem here is the target website is matching with a previous rule before reach the "right" rule. Rules priority are important; we don't evaluate all the rules, just the first rule that output result.

If I move the rule you said to have more priority then tests fail because another website is getting an erroneous value:

```bash
    geek-time: snapshot difference
{
  author: "Gabriel Avner" => "Gabriel AvnerApr 21, 2016"
}
  1) geek-time

  24 passing (3s)
  1 failing

  1) geek-time:
     Error: snapshot difference
{
  author: "Gabriel Avner" => "Gabriel AvnerApr 21, 2016"
}
```

As you can see in these cases we try to do our best effort, but sometimes it's difficult to determinate if the value provided by the rule is good. (This explain why the rule have `strict`, `wrap`, `getValue` functions around, just to be sure value extracted is enough good)

How can we improve this?

**Comment by formatically** [comment]
Thanks for the reply and explanation of line 50!

I think one improvement that can be made is checking to see if a date is present in the "authors" name. 
In your test case, we know that "Gabriel AvnerApr 21, 2016" is bad because it contains a date.  Obviously, that cannot be a name!  

In my tests, I have also found other sources where metascaper extracts an authors name with a date.  This link is an example of that: https://futurism.com/companies-tesla-electric-semi-truck/

I am going to assume that if an extracted name contains two consecutive numbers, then it's not a valid name.   Based on this assumption the following REGEX would improve the quality of extracted names.  

`const REGEX_DATE = /\d{2,}/g`

and then adding it to the Strict function 

```
const strict = rule => $ => {
  const value = rule($)
  return REGEX_STRICT.test(value) && !REGEX_DATE.test(value) && value
}
```

This successfully fixes the issue of your test case and even the example link.

With that added REGEX, the rule `strict(wrap($ => getValue($, $('[class*="author"]'))))` can be given a higher priority than `strict(wrap($ => getValue($, $('[class*="author"] a')))),`

Which I believe, especially with modern websites, would be more accurate.  

Please let me know what you think!
Thanks!

**Comment by Kikobeats** [comment]
It's a good idea 🙂 

currently `REGEX_STRICT` is a bad name this regex. Actually it is checking the author follow the schema:

```text
{FIRT_NAME} {SECOND_NAME}
```

The problem that I'm seeing is that this regex is matching with the bad date value:
https://regex101.com/r/ZBsThD/1

We need to clean the date string from the value and then pass it to `REGEX_STRICT`

**Comment by Kikobeats** [comment]
@formatically I want to ship this enhancement in the next metascraper version. Any idea about how to build a Date regex for clean it from the title?

**Comment by formatically** [comment]
@Kikobeats Sorry for the late response, I went back to school two weeks ago which has kept me busy.  

Did you ever come up with a Regex? If not, I'll work on one and can send it to you to check over.

**Comment by Kikobeats** [comment]
Yes I was thinking of a regex but looks a very long regex handling months names, etc

A Pull Request of this could be awesomeness 🙏

**Comment by formatically** [comment]
Okay, I have given this some thought.  I think, for the time being, it will be best to pass over values that contain a date instead of trying to remove the date from the value.   This way, you do not need to worry about a regex incorrectly removing a date and potentially making the authors name worse off.  

In my tests, I have found that in many cases there is another rule that will pick up the authors name correctly.  

For now, I am testing with this:
`const REGEX_DATE = /\d{2,}/g`

```
const strict = rule => $ => {
  const value = rule($)
  return REGEX_STRICT.test(value) && !REGEX_DATE.test(value) && value
}
```

If a value contains two or more consecutive numbers then its rejected. The assumption is two or more consecutive numbers indicates a date.  

We could also add to this, like month names. 

In my test cases, it has greatly improved the accuracy and it is relatively simple.  All your test cases should still pass too.

**Comment by Kikobeats** [comment]
Looks good for me, can you please create a PR to see if tests pass on green?

PS: Please, enter our [chat](https://chat.microlink.io/) to have a more time real messaging 🙂
