### ISSUE TITLE
Examples using ES modules syntax

### ISSUE THREAD

**Issue by DePasqualeOrg** [microlinkhq/metascraper#550]
I'd like to use this library in a project that uses ES modules. It would be helpful if the readme included examples using ES modules syntax.

**Comment by Kikobeats** [comment]
Hello,

The examples are written in CommonJS because it's the format of the library.

Saying that, you can use it in your ESM project as any other third party CJS loaded in your project:

```js
/* CommonJS */
const metascraper = require('metascraper')

/* ESM */
import metascraper from 'metascraper')
```

**Comment by Kikobeats** [comment]
The whole Node.js is divided into CJS vs ESM modules.

I get what you mean, but since the library is implemented in CJS at this moment, writing examples using ESM syntax is going to give you the false feeling that you're taking ESM benefits (like three shaking) when it's not true.

In case of metascraper user case, I think most of the packages are exporting a default, so rewriting require using import/from instead should be fine.

**Comment by Kikobeats** [comment]
Your code is assuming you have `fetch` and that isn't true until you use Node 18

**Comment by DePasqualeOrg** [comment]
I'm using Node 18.3.0. The output on the console is `[AsyncFunction (anonymous)]`.

**Comment by Kikobeats** [comment]
you missed an `await` there: `const metadata = await metascraper({ html, url });`

**Comment by DePasqualeOrg** [comment]
ESLint says it has no effect, and adding it doesn't change the output.

**Comment by amosbastian** [comment]
I was still getting the following issue when using the above code:

```
No loader is configured for ".node" files: node_modules/.pnpm/re2@1.20.5/node_modules/re2/build/Release/re2.node
```

I found a workaround by doing the following:

```ts
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
import type { Scraper } from "metascraper";

const metascraper: Scraper = require("metascraper")([
  require("metascraper-author")(),
  require("metascraper-audio")(),
  // Add more metascraper plugins as needed
]);
```
