### ISSUE TITLE
[Question] Does it work on Browsers ?

### ISSUE THREAD

**Issue by HamedFathi** [microlinkhq/metascraper#61]
I have a question most of the meta extractors work on node only. 

Does it work on Browsers? 
Do you use this on microlink.js?

**Comment by Kikobeats** [comment]
I don't put effort about run the project into the browser side because I feel it will be so heavy size, specially if you add more plugins for improve data accuracy.

On the other hand, it could be possible sinde we support [.load](https://github.com/microlinkhq/metascraper#metascraperloadrules) method for load rules.

So officially nope but could be possible 🙂

**Comment by Kikobeats** [comment]
Related: https://github.com/microlinkhq/metascraper/issues/57
