### ISSUE TITLE
Incorrect metadata types

### ISSUE THREAD

**Issue by JaneJeon** [microlinkhq/metascraper#666]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

The `Metadata` type exported by metascraper is incorrect.

```ts
  interface Metadata {
    author: string;
    date: string;
    description: string;
    image: string;
    publisher: string;
    title: string;
    url: string;
  }
```

This is what's indicated by the code, but (for obvious reasons) all of these fields are nullable; in fact, some fields may even be missing altogether (if I'm not using, say, `metascraper-description`).

### Steps to reproduce

This is just in the metascraper/index.d.ts code

### Expected behaviour

The types should be changed to indicate that these properties are nullable, _and_ that they may not be present.

### Actual behaviour

Right now, the types indicate that all of these properties are present at all times and all have string values.

**Comment by JaneJeon** [comment]
Oh, `lang` is missing as well (from metascraper-lang)

**Comment by Kikobeats** [comment]
@JaneJeon I will accept a PR fixing this 🙏

**Comment by JaneJeon** [comment]
What is the preferred way to resolve this? Just make the output contain every single possible type and make it nullable (and optional)? Or somehow compose types package by package?

(I have no idea how you would go about approach 2 - my typescript-fu is too weak)

**Comment by Kikobeats** [comment]
Any rule can return string/number/whatever but also null; null means the value isn't being resolved:
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper/src/get-data.js#L6

I think it could be as simple as:

```ts
interface Metadata {
  author: string | null;
  date: string | null;
  description: string | null;
  image: string | null;
  publisher: string | null;
  title: string | null;
  url: string | null;
}
```

About `lang` is missing, it's tricky because every property has its package. The `lang` will be present if metascraper-lang is required: https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-lang.

What could be nice is to add every property added by any metascraper package with a little description, such as:

```ts
interface Metadata {
  /* Get lang property from HTML markup. It will be present when `metascraper-lang` is required */
  lang: string | null
}
```
